# Test Configuration for Deadlock Fix Verification
# Minimal config for quick testing (1-2 training steps)

# Data configuration
data:
  latent_cache_dir: "./latents_cache"
  vae_checkpoint: "/data2/peijia/projects/BioAgent/3D-MedDiffusion/checkpoints/PatchVolume_8x_s2.ckpt"
  normalize_latents: false
  latent_channels: 8

# Model architecture (same as main config)
model:
  model_channels: 128
  channel_mult: [4, 4]
  num_blocks: 5
  attention_levels: [1]
  time_embed_dim: 512
  dropout: 0
  num_heads: 8
  in_channels: 8
  out_channels: 8
  concat_conditioning: true

# Diffusion scheduler
scheduler:
  num_train_timesteps: 1000
  beta_schedule: "linear"
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: "epsilon"
  clip_sample: false

# Training configuration (MINIMAL FOR TESTING)
training:
  batch_size: 2  # Small batch for fast testing
  seed: 42
  gradient_accumulation_steps: 1
  num_epochs: 1  # Only 1 epoch

  # Optimizer
  learning_rate: 1.0e-4
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8
  weight_decay: 0.03

  # Learning rate scheduler
  lr_scheduler_type: "linear"
  warmup_ratio: 0.06
  lr_min: 0.0

  # Mixed precision training
  mixed_precision: "bf16"

  # Gradient clipping
  max_grad_norm: 1.0

  # Validation and checkpointing (FREQUENT FOR TESTING)
  val_every: 1  # Validate every step
  save_every: 100  # Don't save frequently

  # Number of dataloader workers
  num_workers: 2  # Fewer workers for testing

  # Logging
  log_every: 1
  use_wandb: false  # Disable wandb for testing
  wandb_project: "ct-diffusion-test"
  wandb_entity: null
  wandb_run_name: "deadlock-fix-test"
  wandb_tags: ["test", "deadlock-fix"]

# Validation configuration (FAST FOR TESTING)
validation:
  enable_full_validation: true  # Test the fixed function
  full_val_every: 1  # Run full validation every step
  num_samples: 2  # Only 2 samples per process

  # Metrics settings
  data_range: 2.0
  compute_slice_wise: true

  # Distributed evaluation
  distributed_eval: true

# Inference configuration (FAST FOR TESTING)
inference:
  use_ddim: true
  num_inference_steps: 10  # REDUCED from 100 for fast testing
  guidance_scale: 1.0

# Output directories
output:
  checkpoint_dir: "./debug_deadlock/test_checkpoints"
  log_dir: "./debug_deadlock/test_logs"
  visualization_dir: "./debug_deadlock/test_viz"
