data:
  hub_repo: "t2ance/ct-diffusion-256"

  cache_dir: "/data1/peijia/ct"

  vae_checkpoint: "~/projects/BioAgent/3D-MedDiffusion/checkpoints/3DMedDiffusion_checkpoints/PatchVolume_8x_s2.ckpt"

  normalize_latents: false

  latent_channels: 8
model:
  model_channels: 192    =
  channel_mult: [1, 2, 2, 4, 8]
  num_blocks: 3
  attention_levels: [1, 2, 3, 4]
  time_embed_dim: 768
  dropout: 0.3
  num_heads: 12
  in_channels: 8
  out_channels: 8
  concat_conditioning: true

  use_flash_attention: true

scheduler:
  num_train_timesteps: 1000

  beta_schedule: "linear"
  beta_start: 0.0001
  beta_end: 0.02

  prediction_type: "epsilon"

  clip_sample: false

training:
  train_batch_size: 8
  eval_batch_size: 12
  seed: 42

  gradient_accumulation_steps: 8

  num_epochs: 5000

  learning_rate: 3.0e-5
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8
  weight_decay: 0.5

  lr_scheduler_type: "linear"
  warmup_ratio: 0.08
  lr_min: 0.0

  mixed_precision: "bf16"

  max_grad_norm: 1.0

  save_every: 100000
  val_every: 1

  num_workers: 8

  log_every: 1
  use_wandb: true
  wandb_project: "ct-diffusion"
  wandb_entity: null
  wandb_run_name: null
  wandb_tags: ["latent-diffusion", "ct", "3d", "scaled-up"]
  
validation:
  compute_train_metrics: true
  num_samples: 64
  num_visualizations: 1

  data_range:
    2.0

  compute_slice_wise: true

  distributed_eval: true

inference:
  use_ddim: true
  num_inference_steps: 100
  guidance_scale: 1.0

output:
  checkpoint_dir: "./outputs/checkpoints"
  log_dir: "./outputs/logs"
  visualization_dir: "./outputs/visualizations"
